asset:
  name: "Juice Shop"
  description: "OWASP Juice Shop: Probably the most modern and sophisticated insecure web application"
  internet_facing: true
  authn_type: "Password"
  data_classification: "CONFIDENTIAL"

repositories:
  - name: "juice-shop/juice-shop"
    local_path: /data

config:
  llm_provider: openai
  categorization_agent_llm: gpt-4o-mini
  review_agent_llm: gpt-4o-mini
  threat_model_agent_llm: gpt-4o-mini
  report_agent_llm: gpt-4o-mini
  review_max_file_in_batch: 3
